#!/usr/bin/env python3
# coding=utf-8
"""Build the GLM-5.2 DSpark training corpus.

Normalizes the GLM-5.2-FP8-regenerated (on-policy, thinking-hybrid) dataset into a
ShareGPT-style jsonl for SpecForge's ``build_eagle3_dataset`` (``--chat-template
glm-5.2``):

  * ``mgoin/open-perfectblend-glm5.2-regen``   (~1.42M conversations, general chat/math)

Rows use the ShareGPT ``{"from","value"}`` schema; they are normalized to
``[{"role","content"}]`` (the format SpecForge's parser also accepts). Responses are
already generated by GLM-5.2-FP8, so there is NO decode/regeneration here — the target
supplies hidden states online at train time (see GLM52_EXECUTION_DOC.md R-DATA-1/R-DATA-3).

Evaluation uses the dedicated DeepSpec accept-length benchmark suite (gsm8k, math500,
humaneval, ...), NOT a held-out slice of this corpus — so the whole dataset is written
as training data (no eval carve).

Example:
    HF_HOME=/scratch/hf_cache python scripts/prepare_glm52_dspark_data.py \
        --output-dir /scratch/hf_cache/glm52_data
"""

import argparse
import os

from datasets import load_dataset

_ROLE_MAP = {
    "human": "user",
    "user": "user",
    "gpt": "assistant",
    "assistant": "assistant",
    "system": "system",
    "observation": "observation",
    "tool": "tool",
}


def _to_role_content(example):
    """Normalize a row's conversation list to [{"role","content"}]."""
    convs = example.get("conversations")
    out = []
    if convs:
        for m in convs:
            if not isinstance(m, dict):
                continue
            if "role" in m:
                role = m.get("role", "user")
                content = m.get("content", "")
            else:
                role = _ROLE_MAP.get(str(m.get("from", "user")).lower(), "user")
                content = m.get("value", "")
            out.append({"role": str(role), "content": content if content is not None else ""})
    return {"conversations": out}


def _load_conversations(repo: str, num_proc: int):
    ds = load_dataset(repo, split="train")
    ds = ds.map(
        _to_role_content,
        remove_columns=[c for c in ds.column_names if c != "conversations"] + ["conversations"],
        num_proc=num_proc,
        desc=f"normalize {repo}",
    )
    # Drop empty conversations (failed rows).
    ds = ds.filter(lambda x: len(x["conversations"]) >= 2, num_proc=num_proc)
    return ds


def main():
    ap = argparse.ArgumentParser(description="Prepare the GLM-5.2 DSpark corpus")
    ap.add_argument("--mgoin-repo", default="mgoin/open-perfectblend-glm5.2-regen")
    ap.add_argument("--output-dir", required=True)
    ap.add_argument(
        "--total-samples",
        type=int,
        default=0,
        help="Optional cap on the number of training samples. 0 (default) = use the "
        "whole dataset.",
    )
    ap.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Shuffle seed applied before --total-samples capping (ignored when uncapped).",
    )
    ap.add_argument("--num-proc", type=int, default=int(os.environ.get("SPECFORGE_DATA_NUM_PROC", 16)))
    args = ap.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    print(f"Loading {args.mgoin_repo} ...", flush=True)
    ds = _load_conversations(args.mgoin_repo, args.num_proc)
    print(f"available: {len(ds):,}", flush=True)

    if args.total_samples and 0 < args.total_samples < len(ds):
        ds = ds.shuffle(seed=args.seed).select(range(args.total_samples))
    print(f"using: {len(ds):,}", flush=True)

    train_path = os.path.join(args.output_dir, "glm52_dspark_train.jsonl")
    print(f"writing {len(ds):,} train -> {train_path}", flush=True)
    ds.to_json(train_path, lines=True, force_ascii=False)
    print("DONE", flush=True)


if __name__ == "__main__":
    main()
