#!/usr/bin/env python3
# coding=utf-8
"""Build the mixed GLM-5.2 DSpark training corpus.

Mixes two GLM-5.2-FP8-regenerated (on-policy, non-thinking) datasets into a single
ShareGPT-style jsonl for SpecForge's ``build_eagle3_dataset`` (``--chat-template
glm-5.2``), sampled to a target size per the plan (default 1.5M), with a small
held-out eval split:

  * ``mgoin/open-perfectblend-glm5.2-regen``          (~1.42M, general chat/math)
  * ``JessieWei/GLM-5.2-FP8-nemotron-codealpaca``     (~0.8M, code/math)

The two use different conversation schemas ({"from","value"} vs {"role","content"});
both are normalized to ``[{"role","content"}]`` (the format SpecForge's parser also
accepts) so they concatenate cleanly. Responses are already generated by GLM-5.2-FP8,
so there is NO decode/regeneration here — the target supplies hidden states online at
train time (see GLM52_EXECUTION_DOC.md R-DATA-1/R-DATA-3).

Example:
    HF_HOME=/scratch/hf_cache python scripts/prepare_glm52_dspark_data.py \
        --output-dir /scratch/hf_cache/glm52_data \
        --total-samples 1500000 --eval-size 2000
"""

import argparse
import os

from datasets import concatenate_datasets, load_dataset

_ROLE_MAP = {
    "human": "user",
    "user": "user",
    "gpt": "assistant",
    "assistant": "assistant",
    "system": "system",
    "observation": "observation",
    "tool": "tool",
}


def _to_role_content(example):
    """Normalize a row's conversation list to [{"role","content"}]."""
    convs = example.get("conversations")
    out = []
    if convs:
        for m in convs:
            if not isinstance(m, dict):
                continue
            if "role" in m:
                role = m.get("role", "user")
                content = m.get("content", "")
            else:
                role = _ROLE_MAP.get(str(m.get("from", "user")).lower(), "user")
                content = m.get("value", "")
            out.append({"role": str(role), "content": content if content is not None else ""})
    return {"conversations": out}


def _load_conversations(repo: str, num_proc: int):
    ds = load_dataset(repo, split="train")
    ds = ds.map(
        _to_role_content,
        remove_columns=[c for c in ds.column_names if c != "conversations"] + ["conversations"],
        num_proc=num_proc,
        desc=f"normalize {repo}",
    )
    # Drop empty conversations (failed rows).
    ds = ds.filter(lambda x: len(x["conversations"]) >= 2, num_proc=num_proc)
    return ds


def main():
    ap = argparse.ArgumentParser(description="Prepare mixed GLM-5.2 DSpark corpus")
    ap.add_argument("--mgoin-repo", default="mgoin/open-perfectblend-glm5.2-regen")
    ap.add_argument("--codealpaca-repo", default="JessieWei/GLM-5.2-FP8-nemotron-codealpaca")
    ap.add_argument("--output-dir", required=True)
    ap.add_argument("--total-samples", type=int, default=1_500_000)
    ap.add_argument(
        "--mgoin-frac",
        type=float,
        default=None,
        help="Fraction of the mix drawn from the general (mgoin) set. Default: "
        "proportional to the two source sizes.",
    )
    ap.add_argument("--eval-size", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--num-proc", type=int, default=int(os.environ.get("SPECFORGE_DATA_NUM_PROC", 16)))
    args = ap.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    print(f"Loading {args.mgoin_repo} ...", flush=True)
    mg = _load_conversations(args.mgoin_repo, args.num_proc)
    print(f"Loading {args.codealpaca_repo} ...", flush=True)
    ca = _load_conversations(args.codealpaca_repo, args.num_proc)
    print(f"available: mgoin={len(mg):,}  codealpaca={len(ca):,}", flush=True)

    if args.mgoin_frac is None:
        frac = len(mg) / max(1, (len(mg) + len(ca)))
    else:
        frac = args.mgoin_frac
    n_mg = min(len(mg), int(round(args.total_samples * frac)))
    n_ca = min(len(ca), args.total_samples - n_mg)
    # If one source is short, backfill from the other.
    if n_mg + n_ca < args.total_samples:
        n_mg = min(len(mg), args.total_samples - n_ca)
    print(f"sampling: mgoin={n_mg:,} + codealpaca={n_ca:,} = {n_mg + n_ca:,}", flush=True)

    mg = mg.shuffle(seed=args.seed).select(range(n_mg))
    ca = ca.shuffle(seed=args.seed).select(range(n_ca))
    mixed = concatenate_datasets([mg, ca]).shuffle(seed=args.seed)

    eval_size = min(args.eval_size, max(0, len(mixed) - 1))
    eval_ds = mixed.select(range(eval_size))
    train_ds = mixed.select(range(eval_size, len(mixed)))

    train_path = os.path.join(args.output_dir, "glm52_dspark_train.jsonl")
    eval_path = os.path.join(args.output_dir, "glm52_dspark_eval.jsonl")
    print(f"writing {len(train_ds):,} train -> {train_path}", flush=True)
    train_ds.to_json(train_path, lines=True, force_ascii=False)
    print(f"writing {len(eval_ds):,} eval  -> {eval_path}", flush=True)
    eval_ds.to_json(eval_path, lines=True, force_ascii=False)
    print("DONE", flush=True)


if __name__ == "__main__":
    main()
